package com.mapp.flutter.sdk

object Method {
    const val GET_PLATFORM_VERSION = "getPlatformVersion"
    const val ENGAGE = "engage"
    const val SET_DEVICE_ALIAS = "setDeviceAlias"
    const val GET_DEVICE_ALIAS = "getDeviceAlias"
    const val IS_PUSH_ENABLED = "isPushEnabled"
    const val OPT_IN = "optIn"
    const val TRIGGER_IN_APP = "triggerInApp"
    const val IS_READY = "isReady"
    const val GET_DEVICE_INFO = "getDeviceInfo"
    const val FETCH_INBOX_MESSAGE = "fetchInboxMessage"
    const val FETCH_INBOX_MESSAGES = "fetchInboxMessages"
    const val FETCH_INBOX_MESSAGES_WITH_ID = "fetchInBoxMessageWithMessageId"
    const val GET_FCM_TOKEN = "getFcmToken"
    const val SET_TOKEN = "setToken"
    const val START_GEOFENCING = "startGeofencing"
    const val STOP_GEOFENCING = "stopGeofencing"
    const val ADD_TAG = "addTag"
    const val REMOVE_TAG = "removeTag"
    const val GET_TAGS = "getTags"
    const val LOGOUT_WITH_OPT_IN = "logoutWithOptin"
    const val IS_DEVICE_REGISTERED = "isDeviceRegistered"
    const val SET_REMOTE_MESSAGE = "setRemoteMessage"
    const val REMOVE_BADGE_NUMBER = "removeBadgeNumber"
    const val INAPP_MARK_AS_READ = "inAppMarkAsRead"
    const val INAPP_MARK_AS_UNREAD = "inAppMarkAsUnread"
    const val INAPP_MARK_AS_DELETED = "inAppMarkAsDeleted"
    const val PERSMISSION_REQUEST_POST_NOTIFICATION = "requestPermissionPostNotification"
    const val SET_CUSTOM_ATTRIBUTES = "setCustomAttributes"
    const val GET_CUSTOM_ATTRIBUTES = "getCustomAttributes"
}
